name: 同步到1Panel

on:
  schedule:
    - cron: '0 19 * * *'  # 每天凌晨3点（北京时间），GitHub用UTC时区
  workflow_dispatch:      # 手动触发按钮（在Actions标签页）

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 部署到服务器
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "*"
          target: "/vol1/@appshare/1Panel/1panel/www/sites/chenyue.fun/index/"
          rm: true  # 先清空再上传，保持完全一致
